---
--- Generated by Luanalysis
--- Created by 1802.
--- DateTime: 2022/5/15 20:49
---

--参数列表
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]

--数据key
local stockKey = 'seckill:stock:' .. voucherId
local orderKey ='seckill:order:' .. voucherId

--判断库存是否充足
if(tonumber(redis.call('get', stockKey)) <= 0) then
    -- 3.2.库存不足，返回1
    return 1
end
--判断用户是否已下过单sismenber orderkey userid
if(redis.call('sismember', orderKey, userId) == 1) then
    -- 3.3.存在，说明是重复下单，返回2
    return 2
end


--扣减库存 incrby stockKeyey -1
redis.call('incrby',stockKey,-1)
--下单 sadd orderkey userid
redis.call('sadd',orderKey,userId)
--（1）发送消息到队列中，XADD stream.order * k1 v1 k2 v2
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
return 0